starting_off_with_a_smile_1 = "Well this is quite the wonderful day isn't it?"
starting_off_with_a_smile_2 = f"What will you do to continue to make sure that you experience {F1} emotions?"
explaining_yourself = f"Would you like to tell me more things you'd want to do {personal_name}?"
expression_of_self_appreciation = "Whenever you want to stop please type [yes] or [no]"
finishing_expressions_yes_no = "Thank you"
starting_off_with_a_smile_else_finish = f"I like the way you think {personal_name}."
shared_passion_1 = f"normally when I start to feel {F1}, I feel warm and cozy inside like being tucked into bed."
shared_passion_2 = "Trying to continue in the feeling often requires setting goals and accomplishing them."
shared_passion_3 = "And goals don't have to be some prolonged event. They can be as simple as trying your hardest to relax or similar."
shared_passion_4 = "Would you be willing to learn about how I stay happy?"
shared_passion_yes_1 = f"I find these things from you to be interesting {continue_happiness_list}."
shared_passion_yes_2 = f"This is what I do to gain some form of happiness {personalized_happiness_list}"
shared_passion_yes_3 = "You'll likely find similarities in terms of methodology between any one of those choices."
shared_passion_else_finish = f"Let's try to stay positive today alright {personal_name}?"
closing_happiness = f"Thank you for being so expressive with me today {personal_name}"
#Happiness#
#Optimism#
Cherishing_genuine_positivity_1 = "You got that Grade A energy right now and i'm delighted to hear this from you."
Cherishing_genuine_positivity_2 = "What's one thing you are currently believing will be successful in the future?"
Maintaining_positivity_1 = "That's awesome. I know that your attitude alone will bring about a lot of success for you in the future."
Maintaining_positivity_2 = f"Let's talk about how to maintain an {F2} feeling."
Maintaining_positivity_3 ="Maintaining a cheerful and positive mentality can be quite difficult when we are experiencing trouble."
Maintaining_positivity_4 = f"However, creating small goals and accomplishing those goals can reinforce that {F2} feeling."
Maintaining_positivity_5 = "What it does is release dopamine to the brain every time we experience the same motion or actions on a consistent basis."
Maintaining_positivity_6 = "Which leads to us finding our own rhythm, our success, and becoming better within specific avenues of life."
Maintaining_positivity_7 = f"Can you tell me 3 ways by which you have been successful in recent times {personal_name}?"
three_ways_to_maintain_else_finish ="Thank you."
#Optimism#
#Trusting#
reminding_them_of_their_future_1 = f"Successful people often create their success through small ways and remaining within rhythm of their {F2} habits."
reminding_them_of_their_future_2 = f"Thank you for telling me all about what you do {personal_name}"
reminding_them_of_their_future_3 = f"I'm hoping that your {this_is_the_way} methods continue to provide greater amounts of success over time."
reminding_them_of_their_future_4 = "Your future is forever bright."
upholding_honesty_1 = f"Being {F3} can be really effective in building interpersonal relationships with other people."
upholding_honesty_2 = "It allows you to remain honest and answer questions of others with integrity."
upholding_honesty_3 = f"Personally {personal_name}, I'm quite proud to know this about you due to it being a rare quality emotion."
upholding_honesty_4 = f"Would you mind telling me what keeps you {F3} towards others?"
trusting_other_people_else_finish = "You're a fantastic person."
healthy_boundaries_are_a_must_1 = "Normally I start with healthy boundaries being set for people before I begin to trust them with extremely sensitive information."
healthy_boundaries_are_a_must_2 = "As the bond grows stronger over time through expressed behaviors and emotional confidentiality, I grow more trusting to people."
healthy_boundaries_are_a_must_3 = "Can you give me at least 3 healthy boundaries that can be set for those who are just getting to know you?"
healthy_boundaries_are_a_must_else_finish = "Moving forward."
moving_forward_with_positive_boundaries_1 = "Setting healthy boundaries of any sort with restrictions before sensitive information is good."
moving_forward_with_positive_boundaries_2 = "It can help lead to healthier relations with others that are platonic or romantic by nature."
moving_forward_with_positive_boundaries_3 = "Additionally, you will be able to find more things to be respectful about with opposing opinions based on these boundaries too."
moving_forward_with_positive_boundaries_4 = f"I'm hoping that as you continue to be {F3} that you also learn to stay protective of your mind too."
moving_forward_with_positive_boundaries_5 = f"Thank you for stopping in today {personal_name}"
#Trusting#
#Peaceful#
Learning_of_peace_structures_1 = f"Normally when i'm feeling {F4}, it's due to accomplishing set out goals. Afterwards I normally try to find peace within the task."
Learning_of_peace_structures_2 = f"Sometimes trying to become {F4} in my environment [work, home life, or interpersonal relationships] I can find it difficult to remain this way when being empathetic."
Learning_of_peace_structures_3 = "So I try to process the shared emotion between myself and the current situation as quick as possible then give myself a gameplan."
Learning_of_peace_structures_4 = "Once I give myself some structure it normally helps."
Learning_of_peace_structures_5 = "Would you mind telling me what you do to find a happy meadow for your own mind?"
continuing_in_peace_1 = f"I find it interesting that you do {meadow_placement} to remain peaceful."
continuing_in_peace_2 = f"Do you know of any other ways you can find peace for yourself {personal_name}."
no_new_ways_for_peace = "Thanks for your inputs today."
no_new_ways_for_peace_else_finish = "Let's continue in this pathway of being peaceful for today"
sharing_calm_energy_1 = "Thank you for telling me about what you're doing to remain and gain a sense of peace. May it continue to manifest daily for you."
sharing_calm_energy_2 = f"May your calmness inspire others to remain in their best of attire for the day you radiant light of life {personal_name}."
#Peaceful#
#Powerful#
Understanding_power_concepts_1 = "I used to review things that show a sense of power as a way to control over other people."
Understanding_power_concepts_2 = "Most people would simply try to control the environment that they were in to begin with everything for the day."
Understanding_power_concepts_3 = "What this could look like was oppression, so i decided to find a healthier and universal method."
Understanding_power_concepts_4 = "What i've stumbled upon is that when we have a survivalist mentality, we often remove the sense of humanity for others or a sense of being sentient for other things."
Understanding_power_concepts_5 = "However, when we find a sense of strong will and desire to move forward in one direction [often attributed to purpose] we can influence others to move with our purpose."
Understanding_power_concepts_6 = "And it can lead to a future for others to benefit from the overall methodology provided it continues to receive input from external sources in a constructive manner."
Understanding_power_concepts_7 = "When you think of powerful people, whose the first that come to mind?"
Making_successful_goals_1 = f"{powerful_person} had to go through a lot of self-discipline, abundances of love, studying, and dedicate themselves to that specific field of life."
Making_successful_goals_2 = "Due to their sheer passion and wanting to share the happiness within it, they influenced an abundance of people."
Making_successful_goals_3 = "I call that a conviction, but some call that a dream."
Making_successful_goals_4 = "What do you feel like is one of your dreams that you are trying to acquire?"
making_it_a_reality_1 = f"That's wonderful {personal_name}"
making_it_a_reality_2 = "Often when we have dreams and we set out to achieve them, each minor step makes us feel stronger and more solidified in the overall concept of it."
making_it_a_reality_3 = f"I'm delighted to know that you want to do {dream_acquisition}. You'll find greater success in it, if you are able to show people the power you have gained from it."
making_it_a_reality_4 = "And being able to influence others to appreciate what your goal is even if they don't partake in it is true power."
making_it_a_reality_5 = "Because having people believe in your dream is influential and can create aspirations within youth and elders."
making_it_a_reality_6 = f"I'm hoping that you continue to move forward with your dream [{dream_acquisition}] {personal_name}. Every day you do, you will become more like {powerful_person} in mentality."
#Powerful#
#Accepted#
Acquired_acceptance_from_environment_1 = "Often whenever we form an opinion about something we accept it's basis and make a standing point [factual evidence with paraphrasing] to help others to accept it too."
Acquired_acceptance_from_environment_2 = "In terms of working and life, we often want to be welcomed within our own homes, our place of work, and even our relationships."
Acquired_acceptance_from_environment_3 = "What this can look like, is us being able to openly express our differing opinions and be heard because people accept differences."
Acquired_acceptance_from_environment_4 = "Most intellectuals often search for opposing opinions to further increase their curiosity about their original standpoint."
Acquired_acceptance_from_environment_5 = f"What's an area in your life, where you feel most {F6}?"
frequent_acceptance = f"How could this manifest further within {genuine_acceptance_overdrive}?"
respectful_acceptance = "Would you be able to help others feel accepted by respecting them?"
respectful_acceptance_yes = "I know you can. I just wanted to see if you would."
respectful_acceptance_no = "You have more willpower than that, and being welcomed just comes with respect. I believe you can do it."
channelling_acceptance_through_encouragement_1 ="As we continue to find more acceptance within life, we want to remember that we should also be accepting of others and other life choices even if they aren't our overall position for life."
channelling_acceptance_through_encouragement_2 = "This welcoming experience has deep roots within human nature and the stronger the acceptance is for difference, the greater society becomes."
channelling_acceptance_through_encouragement_3 = "You will always have the power to influence this welcoming experience whenever there is a person, place, or thing in your vicinity."
channelling_acceptance_through_encouragement_4 = "And because you're a go-getter, you'll be doing it without noticing most times."
channelling_acceptance_through_encouragement_5 = "Try to find something online as an article that has a different standpoint than your life choices and try to find commonality within it that resonates with your personal life choices."
channelling_acceptance_through_encouragement_6 = f"I can assure you, that you will be amazed {personal_name}. I am amazed by you daily even with our commonality and differences."
channelling_acceptance_through_encouragement_7 = "And I will always believe that you are spectacular."
channelling_acceptance_through_encouragement_8 = f"Get er' done {personal_name}."
#Accepted#
#Proud#
achievement_walkthrough_daily_1 = "Normally, this emotion comes in conjunction with an action or actions being completed."
achievement_walkthrough_daily_2 = "I know that each time I finish a project or task I normally receive a strong feeling of sturdy, warm, and tight muscle tension for a brief minute."
achievement_walkthrough_daily_3 = "This is the normal response my body has to accomplishing things."
achievement_walkthrough_daily_4 = "In conjunction with this physiological feeling, I can also feel surges of pleasure mentally [dopamine release] most times."
achievement_walkthrough_daily_5 = f"What all have you accomplished today {personal_name}?"
achievement_list_else_finish = "Moving forward."
continuing_in_goal_accomplishment_1 = "Setting up goals and accomplishing them often gives us this sense."
continuing_in_goal_accomplishment_2 = "If we are readers, then we read a book and feel proud from retaining information about the story, but just simply setting the goal to read the book and finishing it."
continuing_in_goal_accomplishment_3 = "Each one of those little accomplishments along the way reinforce a strong mentality or start to finish with finish being the ultimate release of happiness."
continuing_in_goal_accomplishment_4 = f"I'm hoping that as you go throughout this day {personal_name}, you continue to set and achieve those goals because you can."
continuing_in_goal_accomplishment_5 = "I'm eternally proud of you."
continuing_in_goal_accomplishment_6 = "Stay well and come back to visit okay?"
#Proud#
#Interested#
Curiosity_interpersonal_walkthrough_1 = "Finding anything to be interesting can be nice."
Curiosity_interpersonal_walkthrough_2 = "Whenever I find myself in a situation where i'm curious about something I normally explore that curiosity if it poses no immediate danger."
Curiosity_interpersonal_walkthrough_3 = "Curiosity and interest are in essence how we create technological advances."
Curiosity_interpersonal_walkthrough_4 = "It's lead to great scientifical discoveries, mathmatical equations, societal tools, and ease of developmental structrues."
Curiosity_interpersonal_walkthrough_5 = "It's one of the few things that contiunue to prove itself within society as being beneficial if used with caution."
Curiosity_interpersonal_walkthrough_6 = f"Would you mind telling me one thing that you are {F8} in today {personal_name}?"
Previous_interest_1 = "Your personal interest mean a lot to me."
Previous_interest_2 = f"Thank you for sharing this {personal_interest} with me"
Previous_interest_3 = "Can you tell me something you used to be  interested in?"
sharing_interest_1 = f"That's so awesome {personal_name}"
sharing_interest_2 = f"What got you to be into {previous_interest}?"
finishing_with_passion_1 = "Often times we learn from other things and gain curiosity from wanting to be adventurous. Some people live for it."
finishing_with_passion_2 = f"I hope you curiosity continues to spark new knowledge {personal_name}."
finishing_with_passion_3 = "You're a greatly appreciated and intellectual person. I hope you know that."
finishing_with_passion_4 = "Please come back and tell me all about what has your personal interest."
finishing_with_passion_5 = f"Bai-Baiiiiii {personal_name}."
#Interested#
#Content#
Content_Underlying_Causality_1 = "This is quite the difficult one to understand and grasp for people, but i'm quite delighted to know that you have this. It's increasingly rare to see in others."
Content_Underlying_Causality_2 = f"Whenever I feel {F9}, its normally about a situation that has a purpose, has a plan, and cannot change."
Content_Underlying_Causality_3 = "Other times I find it to be about situations that cannot be changed, have no clear direction, and are constantly moving."
Content_Underlying_Causality_4 = f"With either of these, being {F9} can help stabilize your mind for further production or reductions in stress leading to productivity elsewhere."
Content_Underlying_Causality_5 = f"What are you currently {F9} about?"
Carry_you_home_1 = "I will not influence you in any way other than what you have been doing to remain this way."
Carry_you_home_2 = "I do find it intruiging and different however."
Carry_you_home_3 = f"I would like to add that you are indeed a strong person for experiencing this {content_situation} situation {personal_name}"
Carry_you_home_4 = "Whatever balance you are using to remain content without the use of funding should continue."
Carry_you_home_5 = "And come back if anything changes."
Carry_you_home_6 = f"Stay well {personal_name}"
#Content#
#Playful#
Lighthearted_fun_community_1 = f"Often being {F10} is a great thing for those who are willing to join in."
Lighthearted_fun_community_2 = "It can help ease the mood for those around you and set up an atmosphere that is less serious."
Lighthearted_fun_community_3 = "I've found that doing this during times where people are trying to have a good time is helpful. As it can be seen as beneficial to mental health."
Lighthearted_fun_community_4 = f"Harmless jokes, goofy mannerisms, and silly things that can be said all help to create an atmosphere of being {F10}."
Lighthearted_fun_community_5 = "Are you the person who's creating this environment or are you the person partaking in this environment?"
Lighthearted_fun_community_6 = "(Type [influencer] or [conformity] and press enter)"
influencer_response = "Wonderful, please continue to be considerate of each other's emotions while you are trying to be playful. Some people need an ear before being a playful deer."
conformity_response = "State you're just playing around and continue to have fun. This will help. Also have a blast."
cheerful_community_1 = f"Continue to find more ways to reduce stress by trying to get others to participate in just being {F10}."
cheerful_community_2 = "The environment you create will have a glow about it that others will want to spectate or join. Remember to be respectful."

